# This workflow updates the URLs in your Fontello CSS file to point to the correct GitHub Pages URLs.

name: Update Fontello CSS

# This workflow is triggered whenever you push changes to the 'main' branch of your repository.
on:
  push:
    branches:
      - main  # Replace with the name of your default branch if it's not 'main'.

jobs:
  update-fontello-css:
    # This job runs on the latest version of Ubuntu.
    runs-on: ubuntu-latest

    steps:
    # This step checks out a copy of your repository's code.
    - name: Check out code
      uses: actions/checkout@v2

    # This step sets up Node.js version 16.
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # This step updates the URLs in your Fontello CSS file.
    - name: Update Fontello CSS
      run: node update-fontello-css.js

    # This step prints the URL of the updated CSS file.
    - name: Print CSS URL
      run: echo "The updated CSS file can be found at https://${{ github.actor }}.github.io/${{ github.repository }}/css/fontello.css"

    # This step commits and pushes any changes made by the previous step.
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update Fontello CSS URLs" || exit 0  
        git push
